### ISSUE TITLE
Error: The first spike is before t_start

### ISSUE THREAD

**Issue by hcantunc** [OpenSourceBrain/VogelsSprekelerEtAl2011#7]
When I run the `vogelsEtAl2011.py` I get the following error:

```
Traceback (most recent call last):
  File "vogelsEtAl2011.py", line 531, in <module>
    numOfSampledNeuronsPattern1_corr, sampledPopPattern1Spikes_corr, numOfSampledNeuronsControl_corr, sampledPopControlSpikes_corr)
  File "../auxRoutines.py", line 732, in plotFig4Column
    im = plotGrid(ax1, excSpikes, pattern1Spikes, pattern1_stimSpikes, pattern2Spikes, pattern2_stimSpikes, patternIntersectionSpikes, controlSpikes, inhibSpikes)
  File "../auxRoutines.py", line 532, in plotGrid
    grid[x, y] = calculateNeuronFiringRate2(auxIndexExc, excSpikes)
  File "../auxRoutines.py", line 72, in calculateNeuronFiringRate2
    neuronISIs = getNeuronISIs(neuronIndex, popSpikes)
  File "../auxRoutines.py", line 54, in getNeuronISIs
    return np.diff(neuronSpikeTimes)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/function_base.py", line 1926, in diff
    return a[slice1]-a[slice2]
  File "/usr/local/lib/python2.7/dist-packages/neo-0.5.1-py2.7.egg/neo/core/spiketrain.py", line 461, in __sub__
    _check_time_in_range(spikes - time, self.t_start, self.t_stop)
  File "/usr/local/lib/python2.7/dist-packages/neo-0.5.1-py2.7.egg/neo/core/spiketrain.py", line 66, in _check_time_in_range
    (value, t_start))
ValueError: The first spike ([    5.2            5.2            5.2            5.2            5.2
     5.2            5.2            5.2            5.2            5.2
     5.2            5.2            5.2            5.2            5.2
     5.2            5.2            5.3            5.2            5.3
     5.3            5.3            5.3            5.3            5.3
     5.3            5.3            5.3            5.3            5.4
     5.3            5.4            5.3            5.5            5.4
     5.5            5.4            5.4            5.4            5.4
     5.4            5.5            5.4            5.5            5.6
     5.7          122.7            6.3           66.9            6.9
    70.1           65.2           66.1           66.7           67.1
    67.4           67.7           68.            68.3           68.5
    68.7           69.            69.1           69.3           69.5
    69.7           69.8           70.            70.2           70.3
    70.4           70.5           70.7           71.            71.            71.1
    71.            71.3           71.4           71.4           71.4
   498.3          377.4         2217.60000001   160.4            8.5
  1846.7         2008.49999997] ms) is before t_start (600.0 ms)
```

I added the `neuronSpikeTimes.t_start = 0` line to the `getNeuronISIs` function at `auxRoutines.py` and it solved the problem but I don't know if this is a plausible solution.

```
def getNeuronISIs (neuronIndex, popSpikes):
	"Gets the interspike intervals of a neurons within a population"
	neuronSpikeTimes = getNeuronSpikeTimes(neuronIndex, popSpikes)
	if neuronSpikeTimes.size == 0 or neuronSpikeTimes.size == 1:
		return -1 * np.ones(1)
	else:
                neuronSpikeTimes.t_start = 0
		return np.diff(neuronSpikeTimes)
```

**Comment by pgleeson** [comment]
Thanks for your interest in this project @hcantunc and sorry for the delay in getting back to you.

The project is overdue retesting with the latest version of required SW. Which version of PyNN are you using? Neuron or Nest? It seems to be running ok for me locally with Neuron 7.4 and PyNN 0.9.1

@sanjayankur31 do you have any relevant updates from your forks?

**Comment by hcantunc** [comment]
I am also running it with Neuron 7.4 and PyNN 0.9.1. It seems like the root of this problem is the neo package. I downgraded the neo version from 0.5.1 to 0.3.3 and it solved the problem.

**Comment by sanjayankur31** [comment]
Not on the PyNN front. I use PyNEST - the network simulation in pure NEST is up to date. It's a more general version of the simulation though - it enables the user to store different patterns and so on, not just the two shown in the paper. It's designed to run with MPI so the data must be recorded to files and then postprocessed to generate the graphs at the moment.

https://github.com/sanjayankur31/VogelsEtAl2011/tree/nest/NEST

**Comment by sanjayankur31** [comment]
Should've autoclosed by merge of #9 - closing.
